'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ArrowRight,LocateFixed,Search,MapPin,ArrowUpRight,BookOpen } from 'lucide-react';
import { Map } from './map';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { api } from '@/lib/utils';
import { timeLabel } from '@/lib/dates';
import { languages, type KiezSummary, type Neighborhood } from '@/lib/types';
export function Explore({initial}:{initial:KiezSummary[]}){
 const [items,setItems]=useState(initial),[selected,setSelected]=useState(initial[0].neighborhood.id),[query,setQuery]=useState(''),[error,setError]=useState(''),[locating,setLocating]=useState(false);
 useEffect(()=>{const refresh=()=>api<KiezSummary[]>('neighborhoods').then(setItems).catch(()=>{});const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[]);
 const filtered=items.filter(({neighborhood:n})=>[n.name,n.district,...n.aliases].join(' ').toLowerCase().includes(query.toLowerCase()));
 const current=items.find(n=>n.neighborhood.id===selected)!;
 async function locate(){setError('');setLocating(true);try{if(!navigator.geolocation)throw new Error('Location is unavailable in this browser. Search for a Kiez below.');const pos=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));const result=await api<{neighborhood:Neighborhood}>('location',{latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy});setSelected(result.neighborhood.id);setQuery('');}catch(e){setError(e instanceof Error?e.message:'Location access was denied. You can still explore the map and search.');}finally{setLocating(false);}}
 return <section id="neighborhoods" className="explore-section"><div className="section-heading"><div><span className="eyebrow">A FEW STREETS. COUNTLESS STORIES.</span><h2>Find a place. Read its notes.</h2></div><Button variant="outline" onClick={locate} disabled={locating}><LocateFixed size={16}/>{locating?'Finding you…':'Find my Kiez'}</Button></div>{error&&<p className="notice" role="alert">{error}</p>}<div className="explore-layout"><div className="neighborhood-list"><label className="search-field"><Search size={18}/><Input aria-label="Search neighborhoods" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a neighborhood…"/><span>↵</span></label><div className="list-caption">BERLIN & HAMBURG, ONE NOTE AT A TIME <span>{filtered.length.toString().padStart(2,'0')}</span></div>{filtered.map(({neighborhood:n,count})=><button key={n.id} className={`neighborhood-row ${selected===n.id?'active':''}`} onClick={()=>setSelected(n.id)} aria-pressed={selected===n.id}><span className="neighborhood-symbol" style={{background:`${n.color}17`,color:n.color}}><MapPin size={22}/></span><span><strong>{n.name}</strong><small>{n.district} <span>·</span> {count} moments today</small></span><ArrowUpRight size={19}/></button>)}{!filtered.length&&<p className="muted empty-search">No Kiez found. Try Kreuzberg, Neukölln or HafenCity.</p>}<div className="list-note"><span className="live-dot"/> Small neighborhoods. Two cities.<br/><span>More neighborhoods will find their voice.</span></div></div><div className="map-panel"><Map selected={selected} onSelect={n=>setSelected(n.id)}/><div className="map-badge"><span className="live-dot"/> THE NEIGHBORHOOD IS ALIVE</div><div className="map-preview" aria-live="polite"><div className="preview-heading"><div><span className="eyebrow">A MOMENT IN {current.neighborhood.district.toUpperCase()}</span><h3>{current.neighborhood.name}</h3></div><span className="preview-dot" style={{background:current.neighborhood.color}}/></div><p className="preview-quote" dir="auto">{current.latest?`“${current.latest.body}”`:'Waiting'}</p><div className="preview-bottom"><small>{current.latest?`${current.latest.nickname} · ${timeLabel(current.latest.created_at)} · ${languages[current.latest.language as keyof typeof languages]||'Original'}`:'Be the first voice today.'}</small><Link href={`/kiez/${selected}`}>Read notes <ArrowRight size={16}/></Link></div></div><span className="boundary-note">Illustrative neighborhood areas · not official boundaries</span></div></div><div className="explore-footnote"><BookOpen size={15}/><span>Browse freely. To leave a moment, be here.</span><span className="demo-tag">Fictional demo stories</span></div></section>;
}
