'use client';
import { useEffect,useRef,useState } from 'react';
import { Headphones,Languages,Square,Flag,LoaderCircle } from 'lucide-react';
import { Button } from './ui/button';
import { api } from '@/lib/utils';
import { languages,type Language } from '@/lib/types';
export function Listen({id,kind,sourceLanguage}:{id:string;kind:'contribution'|'chronicle';sourceLanguage:string}){
 const [language,setLanguage]=useState<Language>(sourceLanguage in languages?sourceLanguage as Language:'en'),[text,setText]=useState(''),[translated,setTranslated]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(''),[playing,setPlaying]=useState(false),[reported,setReported]=useState(false);
 const [enabled,setEnabled]=useState<Language[]>(Object.keys(languages) as Language[]);
 const audio=useRef<HTMLAudioElement|null>(null),generation=useRef(0);
 function stop(){generation.current++;audio.current?.pause();audio.current=null;setPlaying(false);setBusy('');}
 useEffect(()=>{api<{languages:Language[]}>('capabilities').then(c=>{setEnabled(c.languages);setLanguage(l=>c.languages.includes(l)?l:c.languages[0]||'en');}).catch(()=>{});return()=>{generation.current++;audio.current?.pause();};},[]);
 useEffect(()=>{generation.current++;audio.current?.pause();audio.current=null;setText('');setError('');setPlaying(false);setBusy('');setReported(false);},[id]);
 async function request(mode:'translate'|'speech') {stop();const serial=generation.current;setBusy(mode);setError('');try{const result=await api<{text:string;translated:boolean;audio?:string}>(mode,{kind,id,language});if(serial!==generation.current)return;setText(result.text);setTranslated(result.translated);if(result.audio){const player=new Audio(result.audio);audio.current=player;player.onended=()=>setPlaying(false);player.onerror=()=>{setPlaying(false);setError('Playback failed. Please retry.');};await player.play();if(serial!==generation.current){player.pause();return;}setPlaying(true);}}catch(e){if(serial===generation.current)setError(e instanceof Error?e.message:'Please retry.');}finally{if(serial===generation.current)setBusy('');}}
 return <div className="listen-block"><div className="listen-toolbar"><label className="language-control"><span>Listen in</span><select aria-label="Listening language" value={language} onChange={e=>{stop();setLanguage(e.target.value as Language);setText('');setError('');}}>{enabled.map(l=><option value={l} key={l}>{languages[l]}</option>)}</select></label><Button size="sm" variant="outline" disabled={!!busy} onClick={()=>request('translate')}><Languages size={15}/>Translate</Button><Button size="sm" variant="ghost" onClick={()=>playing||busy?stop():request('speech')}>{busy?<LoaderCircle size={16} className="spin"/>:playing?<Square size={15}/>:<Headphones size={16}/>} {busy?'Cancel':playing?'Stop':'Listen'}</Button>{kind==='contribution'&&<button className="report-button" aria-label={reported?'Reported':'Report this contribution'} disabled={reported} onClick={async()=>{try{await api('report',{id});setReported(true);}catch(e){setError(e instanceof Error?e.message:'Could not report.');}}}><Flag size={14}/>{reported&&'Reported'}</button>}</div>{text&&translated&&<div className="translation"><span className="eyebrow">TRANSLATION · {languages[language]}</span><p lang={language} dir={language==='ar'?'rtl':'auto'}>{text}</p></div>}{error&&<p role="alert" className="notice">{error}</p>}</div>;
}
