import { createHmac, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import { cookies } from 'next/headers';
import { db } from './db';
export class HttpError extends Error { constructor(public status:number,message:string){super(message);} }
const devSecret=randomBytes(32).toString('hex');
function secret() { if(process.env.SESSION_SECRET) return process.env.SESSION_SECRET; if(process.env.NODE_ENV==='production') throw new HttpError(503,'The server needs SESSION_SECRET configured.'); return devSecret; }
export function sign(value:Record<string,unknown>) { const payload=Buffer.from(JSON.stringify(value)).toString('base64url'); return `${payload}.${createHmac('sha256',secret()).update(payload).digest('base64url')}`; }
export function verify(token:string):Record<string,unknown>|null { try {const [payload,signature]=token.split('.'); const expected=createHmac('sha256',secret()).update(payload).digest('base64url'); if(!signature || signature.length!==expected.length || !timingSafeEqual(Buffer.from(signature),Buffer.from(expected))) return null; const data=JSON.parse(Buffer.from(payload,'base64url').toString()); if(typeof data.exp!=='number'||data.exp<Date.now()) return null;return data;}catch{return null;} }
export async function session() {const jar=await cookies(); const existing=jar.get('kiez-session')?.value; const payload=existing?verify(existing):null; const id=typeof payload?.sid==='string'?payload.sid:randomUUID(); if(!payload) jar.set('kiez-session',sign({sid:id,exp:Date.now()+30*86400000}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:30*86400}); const d=await db(); await d.query('INSERT INTO sessions(id) VALUES($1) ON CONFLICT DO NOTHING',[id]); return id; }
export function sameOrigin(request:Request) { const origin=request.headers.get('origin'); if(origin && origin!==new URL(request.url).origin) throw new HttpError(403,'This request must come from Kiez Diary.'); }
export async function rateLimit(key:string,limit:number,seconds=60) { const d=await db(); const row=(await d.query<{hits:number}>(`INSERT INTO rate_limits(key,hits,expires_at) VALUES($1,1,now()+($2*interval '1 second')) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN rate_limits.expires_at<now() THEN 1 ELSE rate_limits.hits+1 END,expires_at=CASE WHEN rate_limits.expires_at<now() THEN now()+($2*interval '1 second') ELSE rate_limits.expires_at END RETURNING hits`,[key,seconds])).rows[0]; if(row.hits>limit) throw new HttpError(429,'A little pause, please. Try again in a minute.'); }
export function authorize(request:Request,name:'CRON_SECRET'|'ADMIN_SECRET') {const value=process.env[name]; if(!value||request.headers.get('authorization')!==`Bearer ${value}`) throw new HttpError(401,'Authorization required.');}
