import { loadEnvConfig } from '@next/env';
import { mkdir, writeFile } from 'node:fs/promises';
import { createChronicle } from '../lib/ai';
import { chronicleModel } from '../lib/openai';
import { makeFixtures } from '../lib/fixtures';
import { diaryDate } from '../lib/dates';

async function main() {
  loadEnvConfig(process.cwd());
  const { entries } = makeFixtures(diaryDate())[0];
  console.log(`Generating with ${chronicleModel()} from ${entries.length} fictional contributions…`);
  const draft = await createChronicle(entries);
  const result = { model: chronicleModel(), generatedAt: new Date().toISOString(), promptVersion: 'chronicle-v1', sources: entries, draft };
  await mkdir('.data', { recursive: true });
  await writeFile('.data/chronicle-rehearsal.json', JSON.stringify(result, null, 2));
  await writeFile('.data/chronicle-rehearsal.md', `# ${draft.title}\n\n${draft.body}\n\n---\nGenerated by ${result.model} from ${entries.length} fictional contributions. Automated coverage and review checks passed; not published to the archive.\n`);
  console.log('Three-stage generation passed. Saved .data/chronicle-rehearsal.md and .json; archive unchanged.');
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : 'Chronicle rehearsal failed.');
  process.exitCode = 1;
});
